<?php
/**
 * Created by PhpStorm.
 * User: lihuosheng
 * Date: 2017/10/17
 * Time: 下午4:18
 */
namespace  app\admin\controller;
use think\Controller;

class  Bis extends Controller{
    //TODO:使用频率高的就用obj
private $obj ;
protected  function _initialize()
{
    parent::_initialize(); // TODO: Change the autogenerated stub
    $this->obj =model('Bis');
}


    //TODO:商户列表
    public function  Index()
    {
        //显示status为1的商户信息
      $res=  $this->obj->getByStatus(1);

       return $this->fetch('',[
           'bis'=>$res
       ]);


    }


    //TODO:申请入驻
    public function Apply()
    {
        //显示status为1的商户信息
        $res=  $this->obj->getByStatus(0);

        return $this->fetch('',[
            'bis'=>$res
        ]);

        return $this->fetch();
    }


    //TODO:删除的商户
    public  function  dellist()
    {
        //显示status为1的商户信息
        $res=  $this->obj->getByStatus(-1);

        return $this->fetch('',[
            'bis'=>$res
        ]);
        return $this->fetch();
    }


    //TODO:编辑(这里有两种方法)
    public  function  detail()
    {
        //获取id
        $id=input('id',0,'intval');
        //根据数据库获取一行信息
        $bis =$this->obj->get(['id'=>$id]);
//        $this->obj =model('BisAccount');
//        $bisdata =$this->obj->getBisById($id);

        $resdata = model('BisAccount')->getAccountById($id);
        $data = model('BisLocation')->getLoactionById($id);

        //获取一级城市信息
        $cities = model('City')->getNormalCitiesByParentId();
        //获取一级分类信息
        $categories =model('Category')->getFirstNomalCategories();

        //获取二级城市分类

        $se_cities =model('City')->getNormalCitiesByParentId(intval($bis['city_id']));

        //获取citi_path里的人二级城市分类getSeCityIdByCityPath
        $city_path = $bis['city_path'];
        $se_city_id =$this->getSeCityIdByCityPath($city_path);


//        $data =input();
//        print_r($data);
//        $resdata =db('bis_account')->where('bis_id',$data['id'])->find();
//        $r = db::
//        dump($resdata);
        return $this->fetch('',
            [
                'seCityId'=>$se_city_id,
                'se_cities'=>$se_cities,
                'bis'=>$bis,
//                'bis'=>$data
            'bisaccount'=>$resdata,
                'bislocation'=>$data,
//                'bisdata'=>$bisdata
            'cities'=>$cities,
                'categories'=>$categories
            ]);
    }


    //TODO:
    public function getSeCityIdByCityPath($city_path)
    {
        if(empty($city_path))
        {
            return '';
        }

        //9,18正则校验([9,18])
        if(preg_match('/,/',$city_path))
        {
            //把字符串按照某个字符分割形成数组
            $cityArray =explode(',',$city_path);
            $se_city_id =$cityArray[1];


            return $se_city_id;
        }


    }
    //TODO:修改状态的方法,商家管理的三个状态
    public  function  status()
    {
        //获取id和status

        $id =input('id',0,'intval');
        $status =input('status',0,'intval');

        //修改bis,bisAccount,bisLocation

        $res_bis =$this->obj->save(['status'=>$status],['id'=>$id]);

        $res_location =model('Bislocation')->save(['status'=>$status],['bis_id'=>$id]);
        $res_account =model('BisAccount')->save(['status'=>$status],['bis_id'=>$id,'is_main'=>1]);
        if($res_bis && $res_location && $res_account)
        {
            $this->success('状态更新成功');
        }
        $this->error('状态更新失败');
    }




}